version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- ps: >-
    dotnet restore Grimaldus.sln

    dotnet build Grimaldus.sln

    dotnet publish ./Grimaldus/Grimaldus.csproj -c Release -r win10-x64
test: off
artifacts:
- path: '\Grimaldus\bin\Release\netcoreapp2.1\win10-x64\publish'
  name: Website
deploy:
- provider: WebDeploy
  aspnet_core_force_restart: true
  server: https://184.173.161.69:8172/MSDeploy.axd?site=chriswoodcodes.net
  website: chriswoodcodes.net
  username: asphost166/chriswood
  password:
    secure: lOSR2fIT6qiJ/CmmAWoa9bhjCLBpSyaffLA18cJ+JD4=
  artifact: Website
  aspnet_core: true
  app_offline: true